use zomatodb;

select *
from customer,foods,order_detail;


#List the top 3 customers who have placed the highest number of orders.
select c.customer_id, c.customer_name, count(o.order_id) as Total_Orders
from customer c
join order_detail o on o.customer_id = c.customer_id
group by c.customer_id, c.customer_name
order by Total_Orders desc
limit 3;


#Find the restaurant that has received the highest average rating.
select restaurant_id, restaurant_name, round(avg(rrating),1) as Average_Rating
from restaurant
group by restaurant_id, restaurant_name
order by Average_Rating desc
limit 1;


#List all orders from order_detail that were delivered in under 30 minutes.
select order_id, timestampdiff(minute,order_time,delivered_time) as Delivery_Time
from order_detail
where timestampdiff(minute,order_time,delivered_time) < 30;


#Calculate the total revenue generated by each food item. Display food_id, food_name
#and Total revenue ordered by total revenue in descending order---
select f.food_id, f.food_name, sum(f.price_per_unit) as Total_Revenue
from foods f
join order_food o on f.food_id = o.food_id
group by f.food_id, f.food_name
order by Total_Revenue desc;


#Find the second highest revenue-generating restaurant.
select r.restaurant_id, r.restaurant_name, sum(f.price_per_unit) as Total_Revenue
from restaurant r
join order_food o on r.restaurant_id = o.restaurant_id
join foods f on f.food_id = o.food_id
group by r.restaurant_id, r.restaurant_name
order by Total_Revenue desc
limit 1
offset 1;


#Find the 5 most popular food items based on the quantity sold.
select f.food_id, f.food_name, sum(quantity) as Quantity_Sold
from order_food o
join foods f on o.food_id = f.food_id
group by f.food_id, f.food_name
order by Quantity_Sold desc
limit 5;


#List the top 3 Zomato employees with the highest average delivery ratings.
select employee_id, employee_name, round(avg(employee_avg_rating),1) as Average_Rating
from zomato_employee
group by employee_id, employee_name
order by Average_Rating desc
limit 3;


#Determine the month with the highest number of total orders placed.
select date_format(order_time,'%Y-%m') as Order_Month, count(*)  as Total_Orders
from order_detail
group by date_format(order_time,'%Y-%m')
order by Total_Orders desc
limit 1;


#Calculate the average order amount for each customer. Order by average order amount in descending order.
select c.customer_id, c.customer_name, round(avg(f.price_per_unit),2) as Average_Amount
from customer c
join order_food o on c.customer_id = o.customer_id
join foods f on o.food_id = f.food_id
group by c.customer_id, c.customer_name
order by Average_Amount desc; 


#Identify the most frequent customer for each restaurant.
select c.customer_id, c.customer_name, r.restaurant_id,  count(o.order_id) as Total_Orders
from customer c 
join order_detail o on c.customer_id = o.customer_id
join restaurant r on r.restaurant_id = o.restaurant_id
group by c.customer_id, c.customer_name,r.restaurant_id
order by Total_Orders desc;


#Calculate the total number of orders placed on weekends.
select count(*) as Weekend_Orders
from order_detail
where dayofweek(order_time) in (1,7); -- sunday = 1, saturday  = 7


#Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends.
select 
case when dayofweek(order_time) in (1,7) then 'Weekend' else 'Weekday' end as Day_Type,
round(avg(timestampdiff(Minute, order_time, delivered_time)),2) as Average_delivery_Time_Minutes
from order_detail
group by Day_Type;


#. List the top 5 most expensive food items. Display food_id, food_name, and price_per_unit for all food items with the highest 5 prices.
select food_id, food_name, price_per_unit
from foods
order by price_per_unit desc
limit 5;


#Find the restaurant with the most diverse menu (i.e., the highest number of food items).
select distinct o.restaurant_id, count(f.food_id) as Total_Food_Items
from foods f 
join order_food o on f.food_id = o.food_id
group by o.restaurant_id
order by Total_Food_Items desc
limit 1;


#Calculate total payment amount for each payment type.
select p.payment_type, sum(f.price_per_unit) as Payment_Amount
from payment_table p 
join order_food o on p.order_id = o.order_id
join foods f on f.food_id = o.food_id
group by p.payment_type
order by Payment_amount desc;